version: "3.4"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports :
      - 32400:32400
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/lmex89/Plex/library:/config
      - /home/lmex89/Plex:/tv
      - /home/lmex89/Plex:/movies
    restart: unless-stopped

